---
      {{ $fileJob := .Values.fileJob -}}
      {{ $db := .Values.config.db -}}
      {{ $es := .Values.config.elastic_search -}}
      {{ $rb := .Values.config.rabbitmq -}}
      {{ $api := .Values.webApi -}}
      {{ $storage := .Values.storage}}
    {{ $dataJson := toPrettyJson $api -}}
---
{{ if $api}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vn-suggestion
spec:

  selector:
    matchLabels:
      app: vn-suggestion
  replicas: 1
  #minimumReplicas: {{$api.replicas}}
  template:
    metadata:
      labels:
        app: vn-suggestion
    spec:
      tolerations:
        - key: "app"
          operator: "Equal"
          value: "xdoc"
          effect: "NoSchedule"
      containers:
        - image: docker.io/nttlong/vn-suggestion:amd.3
          name: vn-suggestion
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
 name: vn-suggestion
 labels:
   app: vn-suggestion
spec:
 type: NodePort
 selector:
   app: vn-suggestion
 ports:
   - name: "vn-suggestion-nod-port"
     protocol: TCP
     port: 8000
     targetPort: 8000
---
{{end}}
---