---
      {{ $fileJob := .Values.fileJob -}}
      {{ $db := .Values.config.db -}}
      {{ $es := .Values.config.elastic_search -}}
      {{ $rb := .Values.config.rabbitmq -}}
      {{ $api := .Values.webApi -}}
      {{ $storage := .Values.storage}}
    {{ $dataJson := toPrettyJson $api -}}
---
{{ if $api}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tika
spec:
  selector:
    matchLabels:
      app: tika
  replicas: 1
  template:
    metadata:
      labels:
        app: tika
    spec:
      tolerations:
        - key: "app"
          operator: "Equal"
          value: "xdoc"
          effect: "NoSchedule"
      containers:
        - image: apache/tika:latest
          name: tika
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9998
---
apiVersion: v1
kind: Service
metadata:
 name: tika
 labels:
   app: tika
spec:
 type: NodePort
 selector:
   app: tika
 ports:
   - name: "tika-nod-port"
     protocol: TCP
     port: 9998
     targetPort: 9998
---
{{end}}
---