---
# Source: lv-files/templates/namespace.yml
apiVersion: v1
kind: Namespace
metadata:
  name: xdoc
---
# Source: lv-files/templates/repository-config.yml
apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJkb2NrZXIubGFjdmlldC52biI6eyJ1c2VybmFtZSI6InB1bGwiLCJwYXNzd29yZCI6IkxhY3ZpZXQjMTIzIiwiZW1haWwiOiJwdWxsQGxhY3ZpZXQudm4iLCJhdXRoIjoiY0hWc2JEcE1ZV04yYVdWMEl6RXlNdz09In19fQ==
kind: Secret
metadata:
  name: harbor-secret-registry
  namespace: xdoc

type: kubernetes.io/dockerconfigjson
---
# Source: lv-files/templates/config-map.yml
apiVersion: v1
kind: ConfigMap
metadata:
  name: ???-config
  namespace: xdoc
data:
  admin_db_name: lv-docs
  db: mongodb%3A%2F%2Fadmin%3AMasan%23123%4010.10.59.112%3A27017
  
  elastic_search: 'false'
  
  rabbitmq.port: '5672'
  rabbitmq.server: 'codx-rabbitmq.rabbitmq.svc.cluster.local'
  rabbitmq.msg: 'xyzdsc-2024'
  rabbitmq.username: 'codx'
  rabbitmq.password: 'Masan#123'
  cache_server: 'lv-file-cache-service.xdoc:11211'
  workers: '1'
  worker_class.uvicorn: 'UvicornWorker' #UvicornH11Worker
  worker_class.h11: 'UvicornH11Worker' #UvicornH11Worker
  worker_class.uvloop: 'uvloop'
  worker_class.trio: 'trio'
  timeout_keep_alive: '30'
  timeout_graceful_shutdown: '30'
  server_type.unvicorn: 'unvicorn'
  server_type.hypercorn: 'hypercorn'
  server_type.default: 'auto'
  h2_max_concurrent_streams: '100'
  web_api_url: ./lvfile
  private_web_api: http://.xdoc:8012/lvfile
  auto_ssl_redirect: 'false'
  use_ssl: ''
---
# Source: lv-files/templates/cache.yml
kind: Service
apiVersion: v1
metadata:
  name: lv-file-cache-service
  namespace: xdoc
  labels:
    app: lv-file-cache-service
spec:
  ports:
    - protocol: TCP
      port: 11211
      targetPort: 11211

  selector:
    app: lv-file-cache
  type: ClusterIP
---
# Source: lv-files/templates/content-service.yml
apiVersion: v1
kind: Service
metadata:
 name: content-service
 namespace: xdoc
 labels:
   app: content-service
spec:

 type: NodePort

 selector:
   app: "content"
 ports:
   - name: "content"
     port: 80
     targetPort: 80
     protocol: TCP

     nodePort: 32227
---
# Source: lv-files/templates/office.yml
kind: Service
apiVersion: v1
metadata:
  name: lv-office-service
  namespace:  xdoc
  labels:
    app: lv-office-service
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      
      nodePort: 32223
      
  
  type: NodePort
  
  selector:
    app: lv-office
---
# Source: lv-files/templates/pdf.yml
kind: Service
apiVersion: v1
metadata:
  name: lv-pdf-service
  namespace:  xdoc
  labels:
    app: lv-pdf-service
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      
      nodePort: 32224
      
  
  type: NodePort
  
  selector:
    app: lv-pdf
---
# Source: lv-files/templates/services.yml
---
apiVersion: v1
kind: Service
metadata:
 name: ???-service
 namespace: xdoc
 labels:
   app: ???-service
spec:

 type: ClusterIP

 selector:
   app: ???
 ports:
   - name: ???
     port: 80
     targetPort: 80
     protocol: TCP
---
# Source: lv-files/templates/tika.yml
apiVersion: v1
kind: Service
metadata:
 name: tika-service
 namespace: xdoc
 labels:
   app: tika-service
spec:
  
 type: NodePort
  
 selector:
   app: tika
 ports:
   - name: "tika-node-port"
     protocol: TCP
     port: 80
     targetPort: 9998
     
     nodePort: 32226
---
# Source: lv-files/templates/video.yml
kind: Service
apiVersion: v1
metadata:
  name: lv-video-service
  namespace:  xdoc
  labels:
    app: lv-video-service
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      
      nodePort: 32225
      
  
  type: NodePort
  
  selector:
    app: lv-video
---
# Source: lv-files/templates/apps.yml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ???
  namespace: xdoc
  annotations:
    description: ...
    keel.sh/releaseNotes: kubernetes-cluster-qc
    keel.sh/policy: "glob:build-*"
    keel.sh/approvals: "0"
    lv-file-meta: |-
        {
          "nested_key": {"requireService":true}
        }
spec:
  selector:
    matchLabels:
      app:  ???
  replicas: 3
  template:
    metadata:
      labels:
        app: ???
    spec:

      
      volumes:
        - name: tmp-files
          emptyDir: { }
        - name: socat-share
          emptyDir: { }
        - name: storage-files
          nfs:
            server: 10.10.59.112
            path: /share/xdoc/temp
      

      containers:

        - image:    docker.io/nttlong/fs-tiny-qc:latest
          name: ???
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: ???-config
        
          args:
            - python3
            - /app/cy_xdoc/server.py
            - bind=0.0.0.0:80
            - content_segment_len=9
            - host_url=https://eoffice-uat.masanappslab.com/lvfile
            - private_web_api=http://???-service.xdoc:80/lvfile
            - remote_office=http://lv-office-service.xdoc:80
            - remote_pdf=http://lv-pdf-service.xdoc:80
            - remote_video=http://lv-video-service.xdoc:80
            - tika_server=http://tika-service.xdoc:80
            - cache_server=lv-file-cache-service.xdoc:11211
            - content_service=http://content-service.xdoc:80
            - generation=
            - process_services_host=http://localhost
            - bind=0.0.0.0:80
            - content_segment_len=9
            
            - elastic_search=false
            
            - db=$(db)
            - admin_db_name=$(admin_db_name)
            - rabbitmq.server=$(rabbitmq.server)
            - rabbitmq.port=$(rabbitmq.port)
            - rabbitmq.msg=$(rabbitmq.msg)
            - rabbitmq.username=$(rabbitmq.username)
            - rabbitmq.password=$(rabbitmq.password)
           
            - workers=1
           
            - server_type=Uvicorn
            - worker_class=httptools
            - timeout_keep_alive=$(timeout_keep_alive)
            - timeout_graceful_shutdown=$(timeout_graceful_shutdown)
            - h2_max_concurrent_streams=$(h2_max_concurrent_streams)
            - vn_suggest_url=$(vn_suggest_url)
            - file_storage_path=/mnt/files
            - process_services_host=http://localhost
            - distribute_lock_server=distribute-lock-service.xdoc:2181
            - use_ssl=$(use_ssl)
        

          volumeMounts:
            - name: tmp-files
              mountPath: /tmp-files
            - name: socat-share
              mountPath: /socat-share
            - name: storage-files
              mountPath: /mnt/files
      imagePullSecrets:
        - name: harbor-secret-registry
---
# Source: lv-files/templates/apps.yml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: content
  namespace: xdoc
  annotations:
    description: ...
    keel.sh/releaseNotes: kubernetes-cluster-qc
    keel.sh/policy: "glob:build-*"
    keel.sh/approvals: "0"
    lv-file-meta: |-
        {
          "nested_key": null
        }
spec:
  selector:
    matchLabels:
      app:  content
  replicas: 2
  template:
    metadata:
      labels:
        app: content
    spec:

      
      volumes:
        - name: tmp-files
          emptyDir: { }
        - name: socat-share
          emptyDir: { }
        - name: storage-files
          nfs:
            server: 10.10.59.112
            path: /share/xdoc/temp
      

      containers:

        - image:    docker.io/nttlong/fs-tiny-qc:latest
          name: content
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: ???-config
        
          args:
            - python3
            - /app/cy_jobs/contents.py
            - private_web_api=http://???-service.xdoc:80/lvfile
            - remote_office=http://lv-office-service.xdoc:80
            - remote_pdf=http://lv-pdf-service.xdoc:80
            - remote_video=http://lv-video-service.xdoc:80
            - tika_server=http://tika-service.xdoc:80
            - cache_server=lv-file-cache-service.xdoc:11211
            - content_service=http://content-service.xdoc:80
            - generation=
            - process_services_host=http://localhost
            - bind=0.0.0.0:80
            - content_segment_len=9
            
            - elastic_search=false
            
            - db=$(db)
            - admin_db_name=$(admin_db_name)
            - rabbitmq.server=$(rabbitmq.server)
            - rabbitmq.port=$(rabbitmq.port)
            - rabbitmq.msg=$(rabbitmq.msg)
            - rabbitmq.username=$(rabbitmq.username)
            - rabbitmq.password=$(rabbitmq.password)
           
            - server_type=Uvicorn
            - worker_class=httptools
            - timeout_keep_alive=$(timeout_keep_alive)
            - timeout_graceful_shutdown=$(timeout_graceful_shutdown)
            - h2_max_concurrent_streams=$(h2_max_concurrent_streams)
            - vn_suggest_url=$(vn_suggest_url)
            - file_storage_path=/mnt/files
            - process_services_host=http://localhost
            - distribute_lock_server=distribute-lock-service.xdoc:2181
            - use_ssl=$(use_ssl)
        

          volumeMounts:
            - name: tmp-files
              mountPath: /tmp-files
            - name: socat-share
              mountPath: /socat-share
            - name: storage-files
              mountPath: /mnt/files
      imagePullSecrets:
        - name: harbor-secret-registry
---
# Source: lv-files/templates/cache.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lv-file-cache
  namespace: xdoc

spec:
  replicas: 1
  selector:
    matchLabels:
      app: lv-file-cache
  template:
    metadata:
      labels:
        app: lv-file-cache
    spec:
      tolerations:
        - key: "app"
          operator: "Equal"
          value: "xdoc"
          effect: "NoSchedule"
      containers:
      - name: file-cache
        image: memcached:latest
        ports:
        - containerPort: 11211
---
# Source: lv-files/templates/office.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lv-office
  namespace: xdoc
spec:
  selector:
    matchLabels:
      app:  lv-office
  replicas: 2
  template:
    metadata:
      labels:
        app: lv-office
    spec:
      volumes:
        - name: storage-files
          nfs:
            server: 10.10.59.112
            path: /share/xdoc/temp
      containers:

        - image: nttlong/lv-libreoffice:1.13
          env:
            - name: MEMCACHED_SERVER
              value: lv-file-cache-service.xdoc:11211
          name: lv-office
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: ???-config
          args: ["80"]
          volumeMounts:
            - name: storage-files
              mountPath: /mnt/files
---
# Source: lv-files/templates/pdf.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lv-pdf
  namespace: xdoc
spec:
  selector:
    matchLabels:
      app:  lv-pdf
  replicas: 2
  template:
    metadata:
      labels:
        app: lv-pdf
    spec:
      volumes:
        - name: storage-files
          nfs:
            server: 10.10.59.112
            path: /share/xdoc/temp
      containers:

        - image: nttlong/lv-pdf:4
          env:
            - name: MEMCACHED_SERVER
              value: lv-file-cache-service.xdoc:11211
          name: lv-pdf
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: ???-config
          args: ["80"]
          volumeMounts:
            - name: storage-files
              mountPath: /mnt/files
---
# Source: lv-files/templates/tika.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tika
  namespace: xdoc
  #namespace: xdoc-web
spec:
  selector:
    matchLabels:
      app: tika
  replicas: 2
  template:
    metadata:
      labels:
        app: tika
    spec:
      tolerations:
        - key: "app"
          operator: "Equal"
          value: "xdoc"
          effect: "NoSchedule"
      containers:
        - image: apache/tika:latest
          name: tika
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9998
---
# Source: lv-files/templates/video.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lv-video
  namespace: xdoc
spec:
  selector:
    matchLabels:
      app:  lv-video
  replicas: 2
  template:
    metadata:
      labels:
        app: lv-video
    spec:
      volumes:
        - name: storage-files
          nfs:
            server: 10.10.59.112
            path: /share/xdoc/temp
      containers:
        - image: nttlong/lv-video:5.2
          env:
            - name: MEMCACHED_SERVER
              value: lv-file-cache-service.xdoc:11211
          name: lv-video
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: ???-config
          args: ["80"]
          volumeMounts:
            - name: storage-files
              mountPath: /mnt/files
---
# Source: lv-files/templates/apps.yml
---
---
# Source: lv-files/templates/ingress.yml
---
---
# Source: lv-files/templates/ingress.yml
---
---
# Source: lv-files/templates/services.yml
---
---
# Source: lv-files/templates/services.yml
---
---
# Source: lv-files/templates/test.yml
###
